[2025-02-27T13:22:33.797+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-27T13:22:32.899581+00:00 [queued]>
[2025-02-27T13:22:33.805+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-27T13:22:32.899581+00:00 [queued]>
[2025-02-27T13:22:33.805+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-27T13:22:33.816+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): create_station_informations_table> on 2025-02-27 13:22:32.899581+00:00
[2025-02-27T13:22:33.821+0000] {standard_task_runner.py:57} INFO - Started process 176 to run task
[2025-02-27T13:22:33.822+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'create_station_informations_table', 'manual__2025-02-27T13:22:32.899581+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpizhlzg3a']
[2025-02-27T13:22:33.824+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask create_station_informations_table
[2025-02-27T13:22:33.866+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-27T13:22:32.899581+00:00 [running]> on host f51c37a32fa6
[2025-02-27T13:22:33.925+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='create_station_informations_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T13:22:32.899581+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T13:22:32.899581+00:00'
[2025-02-27T13:22:33.926+0000] {sql.py:262} INFO - Executing: 
        DO $$
        BEGIN
            -- Check first if a type with the same name exists and drop it if it does
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'velib_station_details') THEN
                EXECUTE 'DROP TYPE IF EXISTS velib_station_details CASCADE';
            END IF;
            -- Then, create the table if it does not exist
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = 'velib_station_details'
            ) THEN
                EXECUTE '
                    CREATE TABLE velib_station_details (
                        station_id BIGINT PRIMARY KEY, 
                        capacity INT,                   
                        lat DOUBLE PRECISION,          
                        lon DOUBLE PRECISION,           
                        name VARCHAR(255)
                    );
                ';
            END IF;
        END
        $$;
    
[2025-02-27T13:22:33.933+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-27T13:22:34.072+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-27T13:22:34.075+0000] {sql.py:375} INFO - Running statement: 
        DO $$
        BEGIN
            -- Check first if a type with the same name exists and drop it if it does
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'velib_station_details') THEN
                EXECUTE 'DROP TYPE IF EXISTS velib_station_details CASCADE';
            END IF;
            -- Then, create the table if it does not exist
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = 'velib_station_details'
            ) THEN
                EXECUTE '
                    CREATE TABLE velib_station_details (
                        station_id BIGINT PRIMARY KEY, 
                        capacity INT,                   
                        lat DOUBLE PRECISION,          
                        lon DOUBLE PRECISION,           
                        name VARCHAR(255)
                    );
                ';
            END IF;
        END
        $$;
    , parameters: None
[2025-02-27T13:22:34.086+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_details, 2200) already exists.
CONTEXT:  SQL statement "
                    CREATE TABLE velib_station_details (
                        station_id BIGINT PRIMARY KEY, 
                        capacity INT,                   
                        lat DOUBLE PRECISION,          
                        lon DOUBLE PRECISION,           
                        name VARCHAR(255)
                    );
                "
PL/pgSQL function inline_code_block line 12 at EXECUTE

[2025-02-27T13:22:34.093+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=create_station_informations_table, execution_date=20250227T132232, start_date=20250227T132233, end_date=20250227T132234
[2025-02-27T13:22:34.100+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task create_station_informations_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_details, 2200) already exists.
CONTEXT:  SQL statement "
                    CREATE TABLE velib_station_details (
                        station_id BIGINT PRIMARY KEY, 
                        capacity INT,                   
                        lat DOUBLE PRECISION,          
                        lon DOUBLE PRECISION,           
                        name VARCHAR(255)
                    );
                "
PL/pgSQL function inline_code_block line 12 at EXECUTE
; 176)
[2025-02-27T13:22:34.127+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-27T13:22:34.160+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
